typography_spectrum: 0.55253
color:
  brandColors:
    - '#eff0f2'
    - '#d3d5d4'
    - '#c1c1c1'
    - '#949597'
    - '#4b565c'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.66481
analytics:
  google: null
  facebook: null
  twitter: null
name: New Shores
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ec70dba-56e1-4799-8ddd-03c80520a744.jpg
title: Experimenting with The Grid
purpose: []
