name: New Shores
favicon: null
layout_spectrum: 0.5193991581909359
typography_spectrum: 0.9391839713789523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
