name: New Shores
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9391839713789523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf6f2'
    - '#06171e'
    - '#2b3e44'
    - '#97a4ad'
    - '#ae805f'
  brandStrength: 1
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
