name: New Shores
favicon: null
layout_spectrum: 0.51599
typography_spectrum: 0.55253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff0f2'
    - '#d3d5d4'
    - '#c1c1c1'
    - '#949597'
    - '#4b565c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
